### ISSUE TITLE
The site datex2.eu is not able to send emails (Bugzilla Bug 13)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#13]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 13
Date: 1925-02-19T16:14:44+01:00
From: @ingeniumfaber
To:   bugzilla admin &lt;<webmaster@datex2.eu>&gt;

Last updated: 2019-03-01T12:19:09+01:00

**Comment by greenback-quesq** [comment]
It's old...
