### ISSUE TITLE
IMPORTED (232) - Requirment missing to ensure unique namespaces (Bugzilla Bug 21)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#21]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 21
Date: 2019-02-28T16:29:57+01:00
From: @ingeniumfaber
To:   @JosefKaltwasser

Last updated: 2022-02-28T10:01:53+01:00

**Comment by JosefKaltwasser** [comment]
Done:
6.9.6 The values of the “name” and “prefix” UML Properties shall be unique for all DATEX II packages with “D2Namespace” or “ExternalNamespace” stereotype assigned
(Nimbering from Enquiry version)
