### ISSUE TITLE
IMPORTED (231) - temporary alternating one-way road / lane / carriageway (Bugzilla Bug 22)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#22]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 22
Date: 2019-02-28T16:29:57+01:00
From: @ingeniumfaber
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;
CC:   @iancornwellmottmac

Last updated: 2023-11-28T13:37:54+01:00

**Comment by iancornwellmottmac** [comment]
Added new literal alternatingDirectionTraffic. If "singleLineAlternateTraffic" is considered unsuitable then we have to be explicit in the new literal that it is the direction that alternates.

**Comment by adityatriwibowo1992-source** [comment]
-
