### ISSUE TITLE
IMPORTED (230) - UML qualifiers not mentioned in main section of prEN 16157-1 (Bugzilla Bug 23)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#23]
[Deprecation of qualifier.pdf](https://github.com/user-attachments/files/16066755/Deprecation.of.qualifier.pdf)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 23
Date: 2019-02-28T16:29:57+01:00
From: @ingeniumfaber
To:   @JosefKaltwasser

Last updated: 2022-04-04T16:42:15+02:00

**Comment by JosefKaltwasser** [comment]
Done, added to text of 16157-1.
