### ISSUE TITLE
LinearLocation SingleRoadLinearLocation issue (Bugzilla Bug 252)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#252]
![linearreference](https://github.com/DATEX-II-EU/DatexII/assets/75827629/13c49c7f-fcbc-4355-bbfd-c8e882ed659b)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 252
Date: 2019-04-08T11:29:29+02:00
From: @NdwMartin
To:   Jean-Philippe Mechine &lt;<Jean-Philippe.Mechin@cerema.fr>&gt;
CC:   @iancornwellmottmac

Last updated: 2019-09-06T11:32:16+02:00

**Comment by LBlaive** [comment]
Agree with Ian’s comment. Therefore, it seems wise to undertake no supplementary actions on the data model.

**Comment by iancornwell1** [comment]
Part of my 2019 comment is bogus - you can even have permutations like AlertC + OpenLR in a single instance - being AlertC it will have to be a SingleRoadLinearLocation, which inherits the relationships with OpenLR from its parent - I recall now this was the intention agreed when we chose this design which is a good design. So even more reason to agree there should be no change.

**Comment by LBlaive** [comment]
During the meeting it was agreed to undertake no action and close this issue.
