### ISSUE TITLE
IMPORTED (227) - UML profile association - issues related to EA (Bugzilla Bug 26)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#26]
[RE composite in UML profile manifests as shared aggregation in UML model.zip](https://github.com/user-attachments/files/16066796/RE.composite.in.UML.profile.manifests.as.shared.aggregation.in.UML.model.zip)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 26
Date: 2019-02-28T16:29:57+01:00
From: @ingeniumfaber
To:   @JosefKaltwasser
CC:   @iancornwellmottmac

Last updated: 2024-06-03T11:22:10+02:00

**Comment by JosefKaltwasser** [comment]
Done, 16157-1 and the UML Profile are now based on Association.
