### ISSUE TITLE
Governance of multiple extensions on the same class in different namespaces (Bugzilla Bug 260)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#260]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 260
Date: 2019-05-08T15:36:01+02:00
From: @NdwMartin
To:   @JosefKaltwasser
CC:   @iancornwellmottmac

Last updated: 2022-10-12T15:12:30+02:00

**Comment by JosefKaltwasser** [comment]
Done, with prefixing element names:
Where “_”SomeClassExtensionType” is defined as:
<xs:complexType name=”_”SomeClassExtensionType>
<xs:sequence>
<xs:element name=”_”NamespaceA+ClassA type=NamespaceA””:ClassA minOccurs=”0” />
<xs:element name=”_”NamespaceB+ClassB type=NamespaceB””:ClassB minOccurs=”0” />
...
