### ISSUE TITLE
Rephrase definition of Level A to avoid implication to need whole model (Bugzilla Bug 262)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#262]
[Level A conformance for DATEX.docx](https://github.com/user-attachments/files/16066806/Level.A.conformance.for.DATEX.docx)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 262
Date: 2019-05-24T17:01:38+02:00
From: @iancornwellmottmac
To:   @JosefKaltwasser

Last updated: 2022-05-04T09:39:33+02:00

**Comment by JosefKaltwasser** [comment]
Done:
DATEX II models enable application specific extensions. These extensions may implement innovative concepts, and while they may happily reuse data types, enumerations, components and even identifiable entities from an existing model, they cannot seek any type of system level interoperability with systems being implemented without being cognizant of this particular extension. Such extensions are denoted as Level C extensions.
In other scenarios, extensions seek to add some limited amount of application specific business logic whilst at the same time requiring backward compatibility with an existing model. “Compatibility” here means system level interoperability, e.g. for systems exchanging XML messages a valid instance of an extended model shall always be also a valid instance for the core model. This level of interoperability is in DATEX II denoted as Level B extension. The levels' names actually indicate a compatibility hierarchy where the top level (maximum compatibility) is denoted as Level A, where both interacting systems use components of
