### ISSUE TITLE
Mapping of "abstract" missing in Annex A3 of 16157-1 (Bugzilla Bug 265)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#265]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 265
Date: 2019-07-01T15:43:17+02:00
From: @JosefKaltwasser
To:   @JosefKaltwasser

Last updated: 2022-02-28T10:08:23+01:00

**Comment by JosefKaltwasser** [comment]
Done:
A.3.4.1.11 The “isAbstract” property value of UML classes is mapped to an XML attribute setting of 'abstract = ”true”' in generated XSD complex type definitions.
