### ISSUE TITLE
Recommendation for UUID instead GUID (Bugzilla Bug 285)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#285]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 285
Date: 2020-03-24T15:51:12+01:00
From: @JoergFst
To:   @JosefKaltwasser
CC:   @iancornwellmottmac

Last updated: 2020-12-18T11:08:55+01:00

**Comment by JosefKaltwasser** [comment]
Done with UUIDs and subsequent version numbers recommended.
