### ISSUE TITLE
Not all internal names start with '_' (Bugzilla Bug 287)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#287]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 287
Date: 2020-05-04T09:32:24+02:00
From: @JosefKaltwasser
To:   @JosefKaltwasser
CC:   @jonas-jaderberg

Last updated: 2023-02-13T11:32:30+01:00

**Comment by JosefKaltwasser** [comment]
Done:
<xs:attribute name=”_id” type=”xs:string” use=”required” />
<xs:attribute name=”_version” type=”xs:string” use=”required” />
