### ISSUE TITLE
Deprecate schemaInclude (Bugzilla Bug 288)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#288]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 288
Date: 2020-05-04T09:35:35+02:00
From: @JosefKaltwasser
To:   @JosefKaltwasser
CC:   @iancornwellmottmac

Last updated: 2022-02-17T18:55:52+01:00

**Comment by JosefKaltwasser** [comment]
Done - no longer in the document.
