### ISSUE TITLE
Allow EA Notes for supplementary documentation (Bugzilla Bug 305)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#305]
[Detailed proposal to use EA Notes (1).docx](https://github.com/user-attachments/files/16066836/Detailed.proposal.to.use.EA.Notes.1.docx)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 305
Date: 2020-09-01T17:58:17+02:00
From: @iancornwellmottmac
To:   @JosefKaltwasser

Last updated: 2022-02-28T10:24:26+01:00

**Comment by JosefKaltwasser** [comment]
Done:
NOTE Further documentation can be provided using UML Core::Basic::Comment.

plus

<xs:documentation>
ContentOfComment.BodyPropertyFromUMLModel
</xs:documentation>
