### ISSUE TITLE
New compliance literals (Bugzilla Bug 325)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#325]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 325
Date: 2020-12-22T13:17:13+01:00
From: @JoergFst
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;
CC:   @iancornwellmottmac

Last updated: 2023-11-28T14:07:22+01:00

**Comment by iancornwellmottmac** [comment]
done
