### ISSUE TITLE
Avoid dependency on XML Schema (Bugzilla Bug 351)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#351]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 351
Date: 2021-05-17T10:24:23+02:00
From: @iancornwellmottmac
To:   @JosefKaltwasser

Last updated: 2022-04-22T13:21:02+02:00

**Comment by JosefKaltwasser** [comment]
Done regarding allocation of properties; facest obsoleted by #519
