### ISSUE TITLE
Error in CommonExtension (Bugzilla Bug 370)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#370]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 370
Date: 2021-08-12T12:36:29+02:00
From: @JosefKaltwasser
To:   @JosefKaltwasser
CC:   @iancornwellmottmac

Last updated: 2022-11-15T14:18:58+01:00

**Comment by VictoriaSteinerAC** [comment]
Clas "Speed" has been moved to CommonExtension in the Draft that has been delivered for CEN review.

**Comment by iancornwell1** [comment]
The change to resolve this issue wasn't sufficient.
The class Speed was moved to CommonExtension, but it uses a UnitOfSpeedEnum that remained in the TrafficRegulation namespace!

This means that the dependency from CommonExtension to TrafficRegulation was not removed, and these namespaces have now been declared stable for v3.
This is similar to issue 371 where we decided not to make a breaking change but to suggest a workaround, which for the present issue would be that users of CommonExtension who do not require TrafficRegulation should profile out the optional class Speed.

Now that this kind of bug - undesired namespace dependency - has happened multiple times, we should probably consider what checks we should introduce to avoid it before making releases.

**Comment by iancornwell1** [comment]
A further note about the impact of this bug - users assembling models from modules should already be aware that the order in which modules are imported is important. If module A uses a type in module B then module B must be imported before module A, or else the modelling tool will not be able to resolve the reference to the type when importing A alone. The UnitOfSpeedEnum bug in release 3.6 means that CommonExtension has an undesired dependency on TrafficRegulation. so if a modeller wants to assemble a model that uses that type, TrafficRegulation must be imported before CommonExtension.
