### ISSUE TITLE
Violation of DATEX II Methodoloy, clause 8.2.6 (Bugzilla Bug 372)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#372]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 372
Date: 2021-08-12T13:03:32+02:00
From: @JosefKaltwasser
To:   @JoergFst

Last updated: 2021-08-12T13:03:32+02:00

**Comment by JoergFst** [comment]
Note that this kind of construct is the design of Facility namespace, and there are a couple of those specialisations from other namespaces into the Facility namespace. Changing that to Level-B extensions would be a massive change to existing data models and hinder it's usability.

**** TMB decided on 04/09/24 to allow those specialisations through namespaces ****

The point will become an issue for current comment resolution for Part 1.
