### ISSUE TITLE
Inconsistency between required XML schema namespace URLs and current practice (Bugzilla Bug 389)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#389]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 389
Date: 2021-12-15T11:40:36+01:00
From: @iancornwellmottmac
To:   @JosefKaltwasser
CC:   @jonas-jaderberg

Last updated: 2023-10-13T15:25:33+02:00

**Comment by JosefKaltwasser** [comment]
Done:
The target namespace of each schema is: http://datex2.eu/schema/4/package, where package is the name of the package in LCC.
