### ISSUE TITLE
Include a JSON mapping in 16157-1 (Bugzilla Bug 396)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#396]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 396
Date: 2022-02-15T17:34:03+01:00
From: @iancornwellmottmac
To:   @JosefKaltwasser

Last updated: 2022-02-28T11:01:25+01:00

**Comment by JosefKaltwasser** [comment]
Done:
Further to the UML modelling, this document also defines the mapping of this model to the eXtensible Markup Language (XML), used for formatting data in DATEX II data exchanges. XML, being a widely used method nowadays of formatting data for business-to-business data exchange over the Internet, is one of the possible solutions for mapping the UML modelling into formatted data. Other methods like UPER based on ASN.1 defined by ISO/IEC 8825-2 and JSON Schema defined by https://json-schema.org/draft/2020-12/json-schema-core.html can also be considered and will potentially be specified in further standards in this series. It should also be noted that this standard describes a framework for DATEX II data that is usable for dynamic data messaging services. Other use cases like for example map update exchange may benefit from other frameworks like e.g. Geography Markup Language (GML). Thus, not all parts of the EN 16157 series will conform to all requirements of this document.
