### ISSUE TITLE
HeaderInformation could be moved to PayloadPublication (Bugzilla Bug 405)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#405]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 405
Date: 2022-04-27T17:29:28+02:00
From: @iancornwellmottmac
To:   @ingeniumfaber

Last updated: 2024-05-16T17:28:10+02:00

**Comment by JoergFst** [comment]
Please ignore my comment above.
Final solution for the HeaderInformation class in V4 is:
* Header information class stays in common
* Aggregation to any payload publication will be removed
* Aggregation to Situation will stay in place
* Aggregation to MessageContainer will be added (so will be accessible via Exchange)
