### ISSUE TITLE
"traffic regulation" definition using "highway network" which shall be "road network" (Bugzilla Bug 408)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#408]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 408
Date: 2022-08-11T09:56:38+02:00
From: @vlcinsky
To:   @JosefKaltwasser

Last updated: 2022-08-11T09:56:38+02:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
