### ISSUE TITLE
Element objectReference in SituationReference suboptimal/buggy (Bugzilla Bug 427)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#427]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 427
Date: 2022-11-28T18:19:00+01:00
From: @JoergFst
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;
CC:   @iancornwellmottmac

Last updated: 2023-11-28T14:37:18+01:00

**Comment by iancornwellmottmac** [comment]
done
