### ISSUE TITLE
Add "TunnelCategoryEnum" in the TraficRegulation namespace to comply RTTI DR and ADR (Bugzilla Bug 429)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#429]
[ADR - chapters1.9 & 8.6 - Tunnel restrictions.pdf](https://github.com/user-attachments/files/16066927/ADR.-.chapters1.9.8.6.-.Tunnel.restrictions.pdf)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 429
Date: 2022-12-05T17:53:24+01:00
From: Renan PERROT &lt;<renan.perrot@cerema.fr>&gt;
To:   @VictoriaSteinerAC
CC:   @paalaas

Last updated: 2024-02-08T11:52:38+01:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
