### ISSUE TITLE
Clause required that forbids names ending with "...Helper" (Bugzilla Bug 443)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#443]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 443
Date: 2023-05-15T16:34:55+02:00
From: @VictoriaSteinerAC
To:   @JosefKaltwasser

Last updated: 2023-09-25T12:51:39+02:00

**Comment by JosefKaltwasser** [comment]
Done:
5.3.7 To ensure that the mapping to platforms that do not allow any special characters is possible, the upper-case letter “G” for ending a DATEX II name is reserved for the purpose of generating internal names. Hence, a DATEX II name used in the UML model shall not end with the upper-case letter “G” to avoid name collisions.
