### ISSUE TITLE
Literal names of PriorityRuleType Enumeration not sufficient (Bugzilla Bug 456)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#456]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 456
Date: 2023-08-17T14:13:33+02:00
From: @VictoriaSteinerAC
To:   @VictoriaSteinerAC
CC:   @paalaas

Last updated: 2024-02-08T11:45:24+01:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
