### ISSUE TITLE
Adapt concept of codelists in DATEX II Methodology (Bugzilla Bug 459)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#459]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 459
Date: 2023-09-15T11:47:03+02:00
From: @VictoriaSteinerAC
To:   @JosefKaltwasser

Last updated: 2023-09-15T16:10:01+02:00

**Comment by JosefKaltwasser** [comment]
Done:
6.5.1 Figure 4 depicts the stereotype “D2Datatype” used in general for defining DATEX II datatypes. External datatypes may also be used by declaring them using the “ExternalType” stereotype. The stereotype “D2Codelist” is introduced for datatypes that represent externally maintained lists of codes.
