### ISSUE TITLE
Part 1 should mention other types of publications, like used for TN-ITS. (Bugzilla Bug 460)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#460]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 460
Date: 2023-09-20T13:08:07+02:00
From: @JosefKaltwasser
To:   @JosefKaltwasser

Last updated: 2023-09-25T12:49:25+02:00

**Comment by JosefKaltwasser** [comment]
Integrated in the Text for CEN Enquiry.
