### ISSUE TITLE
Typo in name of enumeration "StandingOrParkingRestricitonTypeEnum" (Bugzilla Bug 461)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#461]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 461
Date: 2023-09-25T15:28:52+02:00
From: @VictoriaSteinerAC
To:   @VictoriaSteinerAC
CC:   @paalaas

Last updated: 2023-09-28T15:10:50+02:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
