### ISSUE TITLE
Unused enumeration "BendOfPriorityRoadTypeEnum" (Bugzilla Bug 462)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#462]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 462
Date: 2023-09-26T12:13:33+02:00
From: @VictoriaSteinerAC
To:   @VictoriaSteinerAC
CC:   @paalaas

Last updated: 2024-02-08T11:46:52+01:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
