### ISSUE TITLE
Signs are not only identified by a number (Bugzilla Bug 465)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#465]
![Schermafbeelding 2023-11-17 105603](https://github.com/DATEX-II-EU/DatexII/assets/75827629/ad02cdf1-87b3-4f42-875f-7d51ab1beb0b)
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 465
Date: 2023-11-17T10:59:14+01:00
From: Bard de Vries &lt;<b.devries@u-trex.nl>&gt;
To:   @VictoriaSteinerAC
CC:   @paalaas

Last updated: 2024-02-08T11:00:23+01:00

**Comment by VictoriaSteinerAC** [comment]
This request has been integrated into the WD that has been delivered to CEN for CIB.
