### ISSUE TITLE
Link onwebsite borken (Bugzilla Bug 468)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#468]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 468
Date: 2023-11-29T12:48:33+01:00
From: @JosefKaltwasser
To:   @NdwMartin
CC:   webmaster@datex2.eu

Last updated: 2023-11-29T12:48:33+01:00

**Comment by NdwMartin** [comment]
This works now
