### ISSUE TITLE
Reduce need for duplication of data in SituationRecords (Bugzilla Bug 469)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#469]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 469
Date: 2023-12-19T18:56:37+01:00
From: @iancornwellmottmac
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;

Last updated: 2023-12-19T18:56:37+01:00

**Comment by iancornwellmottmac** [comment]
Resolved by agreed structural changes made in v4 draft
