### ISSUE TITLE
allowedDeliveryChannel missing in situation record (Bugzilla Bug 470)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#470]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 470
Date: 2024-01-03T16:18:50+01:00
From: @ingeniumfaber
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;

Last updated: 2024-01-03T16:18:50+01:00

**Comment by iancornwellmottmac** [comment]
added
