### ISSUE TITLE
Typo in MobilityTypeEnum definition (Bugzilla Bug 473)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#473]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 473
Date: 2024-02-15T13:57:11+01:00
From: Edgar van Wilgenburg &lt;<edgar.van.wilgenburg@ndw.nu>&gt;
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;

Last updated: 2024-02-15T13:57:11+01:00

**Comment by iancornwellmottmac** [comment]
Resolved (although currently it's SituationElement anyway)

**Comment by iancornwellmottmac** [comment]
Since this is only a description change, it can also be fixed in release 3.6 (where should be SituationRecord), so keeping this issue open until a fix is also committed in the v3 support branch.

**Comment by iancornwellmottmac** [comment]
Also applied in v3 support (actually it's the 'c' that was missing as one can see above). Committed in revision 1381.
