### ISSUE TITLE
Namespace URI from ExternalNamespace not mapped (Bugzilla Bug 476)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#476]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 476
Date: 2024-03-14T17:09:54+01:00
From: @JosefKaltwasser
To:   @JosefKaltwasser

Last updated: 2024-03-18T13:13:43+01:00

**Comment by JosefKaltwasser** [comment]
Essentially done, but fonts got mixed up, sp I keep the issue.
