### ISSUE TITLE
Name clash for uniqueness constraint if two classes from different NS have the same name (Bugzilla Bug 477)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#477]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 477
Date: 2024-03-14T17:13:06+01:00
From: @JosefKaltwasser
To:   @JosefKaltwasser

Last updated: 2024-03-18T13:00:29+01:00

**Comment by JosefKaltwasser** [comment]
Done:
A.3.5.2 Besides the type itself, an Identity-constraint definition will be created that ensures uniqueness of instances of the type, depending on “_id” or “_id”+”_version”, respectively. This constraint definition has the following structure (example for the versioned case including a “_version” attribute)
<xs:unique name=”_”Element+NamespacePrefix+TargetClass”Constraint”>
