### ISSUE TITLE
Should we prevent identically named classes in the same inheritance tree? (Bugzilla Bug 479)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#479]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 479
Date: 2024-03-21T11:48:30+01:00
From: @iancornwellmottmac
To:   @JosefKaltwasser

Last updated: 2024-03-22T12:12:35+01:00

**Comment by JosefKaltwasser** [comment]
Closed after further discussion via mails on the TB reflector on 21/21 August 2024.
