### ISSUE TITLE
[Bug]: v4 tool check for correct references

### ISSUE THREAD

**Issue by VictoriaSteinerAC** [DATEX-II-EU/DatexII#493]
### What happened?

The current implementation of the v4 tool correctly gives a warning when a D2Attribute of type Reference or VersionedReference has a UML dependeny to a class that is not of stereotype Identifiable or VersionedIdentifiable, However, the tool also gives a warning when the reference is done correctly. I have create a small example, where I have created a small test model:
![grafik](https://github.com/DATEX-II-EU/DatexII/assets/149153538/c1be3f23-4771-487c-8775-830a8d10ded3)
I get the following warnings when creating the schemas:
![grafik](https://github.com/DATEX-II-EU/DatexII/assets/149153538/7f7d5b12-7f55-4349-b9e1-1f212462218f)
For testAttribute2 the warning is correct. However, for testAttribute there should not be a warning.
Here the model I used for testing:
[v4 References Test.zip](https://github.com/user-attachments/files/16108159/v4.References.Test.zip)

### Version

4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonas-jaderberg** [comment]
I agree. My testmodel was wrong.
