### ISSUE TITLE
[Bug]: Package "AreaLocation": recommendation or requirement?

### ISSUE THREAD

**Issue by LBlaive** [DATEX-II-EU/DatexII#506]
### What happened?

Comment reported during the Formal Vote ballot in 2018 by FR (no FR019).
The note related to the "AlertCArea" introduces a recommendation regarding the use of different location tables. If the recommendation is not followed, it becomes impossible to correctly interpret the different instances of this class.
Solution: make the recommendation a requirement.

### Version

3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iancornwellmottmac** [comment]
Agree.

**Comment by LBlaive** [comment]
This issue needs to be addressed. The transformation into a requirement (“shall”) seems pertinent.

**Comment by LBlaive** [comment]
Issue accepted. 
•	The text in the note attached to the “AlertCArea” class in the “AreaLocation” class diagram is modified as follows: “When there are multiple instances of AlertCArea, they shall represent the same location using different location tables.”

**Comment by iancornwell1** [comment]
Also changed the "should" to "shall" in v3 support branch.

**Comment by iancornwell1** [comment]
Released in 3.7 March 2026
