### ISSUE TITLE
[Bug]: Schema generation for profiled model generates too much content

### ISSUE THREAD

**Issue by JosefKaltwasser** [DATEX-II-EU/DatexII#516]
### What happened?

Can it be that the profiling is currently not working? I wanted to have a minimum profile with just the GenericPublication (plus all mandatory stuff for that). What I did is select the current 3.5 full model (see below=), then skipped to 5. Selection, deselected PayloadPublication, then selected GenericPublication. The result is the attached set of all namespaces schemas, without profiling. Did I do anything wrong? Or shall I put an issue into GitHub?
![image](https://github.com/user-attachments/assets/8117d33e-1244-4ebc-91a6-b1b3486e714b)
![image](https://github.com/user-attachments/assets/3fc812e4-34fb-4910-81a6-23ebcb550f05)

### Version

3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonas-jaderberg** [comment]
Fixed and released into production env. It only affected the web tool.
