### ISSUE TITLE
[Bug]: docs site has many URLs that give 404

### ISSUE THREAD

**Issue by iancornwell1** [DATEX-II-EU/DatexII#539]
### Bug description?

In the 4 levels and subsidiary pages, there are links that work and links that produce 404. Somewhere I found links to https://docs.datex2.eu/levels/situation/ and similar, which give 404, whereas https://docs.datex2.eu/levels/mastering/situation/ and similar work fine. Similarly there are links like https://docs.datex2.eu/using which gives 404, while the working page has "levels/" in the URL. An example can be found on the page https://docs.datex2.eu/levels/ - the graphic contains a link to https://docs.datex2.eu/using which gives 404.

### Version

3

**Comment by werkenr** [comment]
Seems to be related to a trailingSlash-property for the underlying static-web-app (which was not set). This causes relative url's to actually go up one level before going to the desired page. For example going to `situation/` from `https://docs.datex2.eu/levels/mastering` will result in `https://docs.datex2.eu/levels/situation/`. Setting the trailingSlash-property to auto will redirect the `https://docs.datex2.eu/levels/mastering` to `https://docs.datex2.eu/levels/mastering/`, from where the relative reference will result in the correct `https://docs.datex2.eu/levels/mastering/situation/`.

Fix has been rolled out.
