### ISSUE TITLE
[Bug]: permittedStandingTime requirement for parkingProhibited

### ISSUE THREAD

**Issue by werkenr** [DATEX-II-EU/DatexII#556]
### Bug description?

It is required to define a permittedStandingTime when a parkingProhibited is used. However, in The Netherlands there is no definition in the regulations how long it is permitted to stand when it is only a parking restriction.
![image](https://github.com/user-attachments/assets/84849606-dd93-4714-81e3-66990343cf52)

### Version

3

**Comment by VictoriaSteinerAC** [comment]
Will be resolved in the next draft of the model (v3.6)
