### ISSUE TITLE
[Bug]: Spelling error limittedTrafficZone literal

### ISSUE THREAD

**Issue by MaryseBucking** [DATEX-II-EU/DatexII#557]
### Bug description?

Within the enumeration ControlledZoneTypeEnum the literal limittedTrafficZone is used. This should be limitedTrafficZone (1 t in limited), see: https://en.wikipedia.org/wiki/Limited_traffic_zone and https://www.merriam-webster.com/dictionary/limited.

### Version

3

**Comment by VictoriaSteinerAC** [comment]
Will be corrected in v3.6
